// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../model/livro';
import { Editora } from '../model/editora';
import { ControleEditoraService } from '../services/controle-editora.service';
import { ControleLivrosService } from '../services/controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Editora[] = [];
  public livros: Livro[] = [];

  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().subscribe(livros => this.livros = livros);
  }

  excluir = (codigo: string) => {
    this.servLivros.excluir(codigo).subscribe(() => {
      this.servLivros.obterLivros().subscribe(livros => this.livros = livros);
    });
  }

  obterNome = (codEditora: number) => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}



<div class="container">
  <h1 class="titulo">Catálogo de Livros</h1>
  <table class="table">
    <thead>
      <tr class="tableHeader">
        <th class="tableCell">Título</th>
        <th class="tableCell">Resumo</th>
        <th class="tableCell">Editora</th>
        <th class="tableCell">Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros; let i = index" [ngClass]="{destaqueCinza: i % 2 === 0, destaqueBranco: i % 2 !== 0}">
        <td class="tableTitulo">
          <div class="tituloWrapper">
            <h3 class="tituloLivro">{{livro.titulo}}</h3>
            
            <button *ngIf="livro.codigo" (click)="excluir(livro.codigo)" class="excluirButton">Excluir</button>
          </div>
        </td>
        <td class="tableCell">{{livro.resumo}}</td>
        <td class="tableCell">{{obterNome(livro.codEditora)}}</td>
        <td class="tableCell">{{livro.autores.join(', ')}}</td>
      </tr>
    </tbody>
  </table>
</div>

// clientes/livros-react/src/LivroLista.js
import { useState, useEffect } from "react";
import { ControleLivros } from "./controle/ControleLivros.ts";
import { ControleEditora } from "./controle/ControleEditora.ts";
import './LivroLista.css';

const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora();

function LinhaLivro(props) {
  const { livro, excluir } = props;
  const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

  const autoresList = livro.autores.map((autor, index) => (
    <li key={index}>{autor}</li>
  ));

  return (
    <tr>
      <td>
        <div className="livro-info">
          <h3>{livro.titulo}</h3>
          <button onClick={() => excluir(livro.codigo)} className="excluir">Excluir</button>
        </div>
      </td>
      <td>{nomeEditora}</td>
      <td>{livro.resumo}</td>
      <td>
        <ul>{autoresList}</ul>
      </td>
    </tr>
  );
}

export default function LivroLista() {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    async function carregaLivros() {
      const livros = await controleLivro.obterLivros();
      setLivros(livros);
      setCarregado(true);
    }
    if (!carregado) {
      carregaLivros();
    }
  }, [carregado]);

  const excluir = (codigo) => {
    controleLivro.excluir(codigo)
      .then(() => setCarregado(false));
  };

  const linhasLivros = livros.map((livro, index) => (
    <LinhaLivro
      key={livro.codigo}
      livro={livro}
      excluir={excluir}
      className={index === 0 ? 'table-header' : ''}
    />
  ));

  return (
    <main style={{textAlign: "left"}}>
      <h1>Catálogo de livros</h1>
      <table>
        <thead>
          <tr>
            <th className="table-header">Título</th>
            <th className="table-header">Editora</th>
            <th className="table-header">Resumo</th>
            <th className="table-header">Autores</th>
          </tr>
        </thead>
        <tbody>{linhasLivros}</tbody>
      </table>
    </main>
  );
}
