// clientes/livros-next/pages/LivroLista.tsx
import React, { useEffect, useState } from 'react';
import styles from '../styles/LivroLista.module.css';
import { Menu } from '../componentes/Menu';
import { ControleLivros } from '../classes/controle/ControleLivros';
import { ControleEditora } from '../classes/controle/ControleEditora';

interface Livro {
  codigo: string;
  titulo: string;
  resumo: string;
  codEditora: number; 
  autores: string[];
}

interface Editora {
  codEditora: number; 
  nome: string;
}

const controleLivros = new ControleLivros();
const controleEditora = new ControleEditora(); 

const LivroLista: React.FC = () => {
  const [livros, setLivros] = useState<Livro[]>([]);
  const [carregado, setCarregado] = useState(false);

  const excluir = (codigo: string) => {
    controleLivros.excluir(codigo)
      .then(() => setCarregado(false));
  };

  useEffect(() => {
    if (!carregado) {
      controleLivros.obterLivros()
        .then((livros) => {
          setLivros(livros);
          setCarregado(true);
        });
    }
  }, [carregado]);

  return (
    <div className={styles.container}>
      <Menu />
      <main className={styles.main}>
        <h1 className={styles.titulo}>Catálogo de Livros</h1>
        <table className={styles.table}>
          <thead>
            <tr className={styles.tableHeader}>
              <th className={styles.tableCell}>Título</th>
              <th className={styles.tableCell}>Resumo</th>
              <th className={styles.tableCell}>Editora</th>
              <th className={styles.tableCell}>Autores</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro, index) => (
              <tr key={index} className={index % 2 === 0 ? styles.destaqueCinza : styles.destaqueBranco}>
                <td className={styles.tituloCell}>
                  <div className={styles.tituloWrapper}>
                    <h3 className={styles.tituloLivro}>{livro.titulo}</h3>
                    <button onClick={() => excluir(livro.codigo)} className={styles.excluirButton}>Excluir</button>
                  </div>
                </td>
                <td className={styles.tableCell}>{livro.resumo}</td>
                <td className={styles.tableCell}>{controleEditora.getNomeEditora(livro.codEditora)}</td> {/* Agora exibe o nome da editora */}
                <td className={styles.tableCell}>{livro.autores.join(', ')}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>
    </div>
  );
};

export default LivroLista;

// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../model/livro';
import { Editora } from '../model/editora';
import { ControleEditoraService } from '../services/controle-editora.service';
import { ControleLivrosService } from '../services/controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  public editoras: Editora[] = [];
  public livros: Livro[] = [];

  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().subscribe(livros => this.livros = livros);
  }

  excluir = (codigo: string) => {
    this.servLivros.excluir(codigo).subscribe(() => {
      this.servLivros.obterLivros().subscribe(livros => this.livros = livros);
    });
  }

  obterNome = (codEditora: number) => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}



<div class="container">
  <h1 class="titulo">Catálogo de Livros</h1>
  <table class="table">
    <thead>
      <tr class="tableHeader">
        <th class="tableCell">Título</th>
        <th class="tableCell">Resumo</th>
        <th class="tableCell">Editora</th>
        <th class="tableCell">Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros; let i = index" [ngClass]="{destaqueCinza: i % 2 === 0, destaqueBranco: i % 2 !== 0}">
        <td class="tableTitulo">
          <div class="tituloWrapper">
            <h3 class="tituloLivro">{{livro.titulo}}</h3>
            
            <button *ngIf="livro.codigo" (click)="excluir(livro.codigo)" class="excluirButton">Excluir</button>
          </div>
        </td>
        <td class="tableCell">{{livro.resumo}}</td>
        <td class="tableCell">{{obterNome(livro.codEditora)}}</td>
        <td class="tableCell">{{livro.autores.join(', ')}}</td>
      </tr>
    </tbody>
  </table>
</div>
